USE [jobs]
GO

/****** Object:  Table [dbo].[_201903v2]    Script Date: 4/28/2019 10:26:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[_201904](
	[job_id] [varchar](20) NOT NULL,
	[monthly_salary] [float] NOT NULL,
	[headcount] [bigint] NOT NULL,
	[title] [varchar](max) NOT NULL,
	[career] [nvarchar](100) NOT NULL,
	[city] [nvarchar](20) NOT NULL,
	[province] [nvarchar](20) NOT NULL,
	[company_description] [nvarchar](max) NOT NULL,
	[company_size] [nvarchar](100) NOT NULL,
	[company_title] [nvarchar](100) NOT NULL,
	[company_type] [nvarchar](100) NOT NULL,
	[ageism] [bit] NOT NULL,
	[db_Apache_Hive] [bit] NOT NULL,
	[db_CouchBase] [bit] NOT NULL,
	[db_CouchDB] [bit] NOT NULL,
	[db_DB2] [bit] NOT NULL,
	[db_DynamoDB] [bit] NOT NULL,
	[db_Elasticsearch] [bit] NOT NULL,
	[db_FileMaker] [bit] NOT NULL,
	[db_Firebase] [bit] NOT NULL,
	[db_Firebird] [bit] NOT NULL,
	[db_Hbase] [bit] NOT NULL,
	[db_Informix] [bit] NOT NULL,
	[db_Ingres] [bit] NOT NULL,
	[db_MariaDB] [bit] NOT NULL,
	[db_Memcached] [bit] NOT NULL,
	[db_MongoDB] [bit] NOT NULL,
	[db_MySQL] [bit] NOT NULL,
	[db_Neo4j] [bit] NOT NULL,
	[db_Netezza] [bit] NOT NULL,
	[db_Oracle] [bit] NOT NULL,
	[db_PostgreSQL] [bit] NOT NULL,
	[db_Redis] [bit] NOT NULL,
	[db_Riak] [bit] NOT NULL,
	[db_SAP_HANA] [bit] NOT NULL,
	[db_SQL_Server] [bit] NOT NULL,
	[db_SQLite] [bit] NOT NULL,
	[db_Solr] [bit] NOT NULL,
	[db_Splunk] [bit] NOT NULL,
	[db_Sybase] [bit] NOT NULL,
	[db_Teradata] [bit] NOT NULL,
	[db_dBase] [bit] NOT NULL,
	[edu] [nvarchar](100) NOT NULL,
	[english] [bit] NOT NULL,
	[experience] [nvarchar](100) NOT NULL,
	[expert_adas] [bit] NOT NULL,
	[expert_blockchain] [bit] NOT NULL,
	[expert_embed] [bit] NOT NULL,
	[expert_expert] [bit] NOT NULL,
	[expert_gis] [bit] NOT NULL,
	[_996_yes] [bit] NOT NULL,
	[_996_no] [bit] NOT NULL,
	[industry] [nvarchar](100) NOT NULL,
	[japanese] [bit] NOT NULL,
	[job_description] [nvarchar](max) NOT NULL,
	[job_summary] [nvarchar](100) NOT NULL,
	[job_tags] [nvarchar](100) NOT NULL,
	[phone_android] [bit] NOT NULL,
	[phone_app] [bit] NOT NULL,
	[phone_iso] [bit] NOT NULL,
	[pl_c_sharp] [bit] NOT NULL,
	[pl_cpp] [bit] NOT NULL,
	[pl_delphi] [bit] NOT NULL,
	[pl_go] [bit] NOT NULL,
	[pl_haskell] [bit] NOT NULL,
	[pl_java] [bit] NOT NULL,
	[pl_javascript] [bit] NOT NULL,
	[pl_julia] [bit] NOT NULL,
	[pl_kotlin] [bit] NOT NULL,
	[pl_lua] [bit] NOT NULL,
	[pl_matlab] [bit] NOT NULL,
	[pl_objective_c] [bit] NOT NULL,
	[pl_perl] [bit] NOT NULL,
	[pl_php] [bit] NOT NULL,
	[pl_python] [bit] NOT NULL,
	[pl_ruby] [bit] NOT NULL,
	[pl_rust] [bit] NOT NULL,
	[pl_scrala] [bit] NOT NULL,
	[pl_swift] [bit] NOT NULL,
	[pl_typescript] [bit] NOT NULL,
	[pl_vba] [bit] NOT NULL,
	[pl_visual_basic] [bit] NOT NULL,
	[publish_date] [datetime] NOT NULL,
	[published_on_weekend] [bit] NOT NULL,
	[tag_baby_care] [bit] NOT NULL,
	[tag_five_insurance] [bit] NOT NULL,
	[tag_flexible] [bit] NOT NULL,
	[tag_no_overtime] [bit] NOT NULL,
	[tag_rest_one_day] [bit] NOT NULL,
	[tag_rest_two_days] [bit] NOT NULL,
	[tag_stock] [bit] NOT NULL,
	[ml_tensorflow] [bit] NOT NULL,
	[ml_caffe] [bit] NOT NULL,
	[ml_cntk] [bit] NOT NULL,
	[ml_chainer] [bit] NOT NULL,
	[ml_mxnet] [bit] NOT NULL,
	[ml_keras] [bit] NOT NULL,
	[ml_deeplearning4j] [bit] NOT NULL,
	[ml_theano] [bit] NOT NULL,
	[ml_sklearn] [bit] NOT NULL,
	[ml_mahout] [bit] NOT NULL,
	[ml_paddlepaddle] [bit] NOT NULL

 CONSTRAINT [PK__201904v22] PRIMARY KEY CLUSTERED 
(
	[job_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


