USE [jobs]
GO

/****** Object:  Table [dbo].[_51jobs]    Script Date: 4/5/2019 2:13:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[_51jobs](
	[ageism] [bit] NOT NULL,
	[career_algorithm] [bit] NOT NULL,
	[career_architect] [bit] NOT NULL,
	[career_software_engineer] [bit] NOT NULL,
	[city_beijing] [bit] NOT NULL,
	[city_changchun] [bit] NOT NULL,
	[city_changsha] [bit] NOT NULL,
	[city_chengdu] [bit] NOT NULL,
	[city_chongqing] [bit] NOT NULL,
	[city_dalian] [bit] NOT NULL,
	[city_dongguan] [bit] NOT NULL,
	[city_fuzhou] [bit] NOT NULL,
	[city_guangzhou] [bit] NOT NULL,
	[city_hangzhou] [bit] NOT NULL,
	[city_harbin] [bit] NOT NULL,
	[city_hefei] [bit] NOT NULL,
	[city_jinan] [bit] NOT NULL,
	[city_kuming] [bit] NOT NULL,
	[city_nanjing] [bit] NOT NULL,
	[city_ningbo] [bit] NOT NULL,
	[city_qingdao] [bit] NOT NULL,
	[city_shanghai] [bit] NOT NULL,
	[city_shenyang] [bit] NOT NULL,
	[city_shenzhen] [bit] NOT NULL,
	[city_tianjin] [bit] NOT NULL,
	[city_wuhan] [bit] NOT NULL,
	[city_xian] [bit] NOT NULL,
	[city_zhengzhou] [bit] NOT NULL,
	[company_description] [varchar](max) NOT NULL,
	[company_size_10000] [bit] NOT NULL,
	[company_size_1000_5000] [bit] NOT NULL,
	[company_size_150_500] [bit] NOT NULL,
	[company_size_50] [bit] NOT NULL,
	[company_size_5000_10000] [bit] NOT NULL,
	[company_size_500_1000] [bit] NOT NULL,
	[company_size_50_150] [bit] NOT NULL,
	[company_title] [varchar](max) NOT NULL,
	[company_tpye_jv] [bit] NOT NULL,
	[company_type_foreign] [bit] NOT NULL,
	[company_type_foreign_gov] [bit] NOT NULL,
	[company_type_foreign_rep] [bit] NOT NULL,
	[company_type_listed] [bit] NOT NULL,
	[company_type_non_profit] [bit] NOT NULL,
	[company_type_private] [bit] NOT NULL,
	[company_type_public_institution] [bit] NOT NULL,
	[company_type_startup] [bit] NOT NULL,
	[company_type_state] [bit] NOT NULL,
	[company_type_us_eu] [bit] NOT NULL,
	[db_Apache_Hive] [bit] NOT NULL,
	[db_CouchBase] [bit] NOT NULL,
	[db_CouchDB] [bit] NOT NULL,
	[db_DB2] [bit] NOT NULL,
	[db_DynamoDB] [bit] NOT NULL,
	[db_Elasticsearch] [bit] NOT NULL,
	[db_FileMaker] [bit] NOT NULL,
	[db_Firebase] [bit] NOT NULL,
	[db_Firebird] [bit] NOT NULL,
	[db_Hbase] [bit] NOT NULL,
	[db_Informix] [bit] NOT NULL,
	[db_Ingres] [bit] NOT NULL,
	[db_MariaDB] [bit] NOT NULL,
	[db_Memcached] [bit] NOT NULL,
	[db_MongoDB] [bit] NOT NULL,
	[db_MySQL] [bit] NOT NULL,
	[db_Neo4j] [bit] NOT NULL,
	[db_Netezza] [bit] NOT NULL,
	[db_Oracle] [bit] NOT NULL,
	[db_PostgreSQL] [bit] NOT NULL,
	[db_Redis] [bit] NOT NULL,
	[db_Riak] [bit] NOT NULL,
	[db_SAP_HANA] [bit] NOT NULL,
	[db_SQL_Server] [bit] NOT NULL,
	[db_SQLite] [bit] NOT NULL,
	[db_Solr] [bit] NOT NULL,
	[db_Splunk] [bit] NOT NULL,
	[db_Sybase] [bit] NOT NULL,
	[db_Teradata] [bit] NOT NULL,
	[db_dBase] [bit] NOT NULL,
	[edu_associate] [bit] NOT NULL,
	[edu_bachelor] [bit] NOT NULL,
	[edu_high_school] [bit] NOT NULL,
	[edu_master] [bit] NOT NULL,
	[edu_middle_school] [bit] NOT NULL,
	[edu_phd] [bit] NOT NULL,
	[english] [bit] NOT NULL,
	[experience_10] [bit] NOT NULL,
	[experience_1_3] [bit] NOT NULL,
	[experience_3_5] [bit] NOT NULL,
	[experience_5_10] [bit] NOT NULL,
	[experience_no] [bit] NOT NULL,
	[icu_996] [bit] NOT NULL,
	[industry_ads] [bit] NOT NULL,
	[industry_computer] [bit] NOT NULL,
	[industry_edu] [bit] NOT NULL,
	[industry_energy] [bit] NOT NULL,
	[industry_finance] [bit] NOT NULL,
	[industry_gov] [bit] NOT NULL,
	[industry_logistic] [bit] NOT NULL,
	[industry_medical] [bit] NOT NULL,
	[industry_realestate] [bit] NOT NULL,
	[industry_service] [bit] NOT NULL,
	[industry_trade] [bit] NOT NULL,
	[japanese] [bit] NOT NULL,
	[job_description] [varchar](max) NOT NULL,
	[job_id] [varchar](max) NOT NULL,
	[monthly_salary] [float] NOT NULL,
	[non_996] [bit] NOT NULL,
	[phone_android] [bit] NOT NULL,
	[phone_app] [bit] NOT NULL,
	[phone_iso] [bit] NOT NULL,
	[pl_c_sharp] [bit] NOT NULL,
	[pl_cpp] [bit] NOT NULL,
	[pl_delphi] [bit] NOT NULL,
	[pl_go] [bit] NOT NULL,
	[pl_haskell] [bit] NOT NULL,
	[pl_java] [bit] NOT NULL,
	[pl_javascript] [bit] NOT NULL,
	[pl_julia] [bit] NOT NULL,
	[pl_kotlin] [bit] NOT NULL,
	[pl_lua] [bit] NOT NULL,
	[pl_matlab] [bit] NOT NULL,
	[pl_objective_c] [bit] NOT NULL,
	[pl_perl] [bit] NOT NULL,
	[pl_php] [bit] NOT NULL,
	[pl_python] [bit] NOT NULL,
	[pl_ruby] [bit] NOT NULL,
	[pl_rust] [bit] NOT NULL,
	[pl_scrala] [bit] NOT NULL,
	[pl_swift] [bit] NOT NULL,
	[pl_typescript] [bit] NOT NULL,
	[pl_vba] [bit] NOT NULL,
	[pl_visual_basic] [bit] NOT NULL,
	[publish_date] [datetime] NOT NULL,
	[published_on_weekend] [bit] NOT NULL,
	[tag_baby_care] [bit] NOT NULL,
	[tag_five_insurance] [bit] NOT NULL,
	[tag_flexible] [bit] NOT NULL,
	[tag_no_overtime] [bit] NOT NULL,
	[tag_rest_one_day] [bit] NOT NULL,
	[tag_rest_two_days] [bit] NOT NULL,
	[tag_stock] [bit] NOT NULL,
	[title] [varchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


